[package]
name = "subkey"
version = "2.0.0"
authors = ["Abel Technologies abelbeertech@outlook.com"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "http://www.abel.beer"
repository = "https://github.com/abelbeertech/abel-bkchain"
readme = "README.md"

[[bin]]
path = "src/main.rs"
name = "subkey"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-runtime = { version = "2.0.0", path = "../../node/runtime" }
node-primitives = { version = "2.0.0", path = "../../node/primitives" }
sc-cli = { version = "0.8.0", path = "../../../client/cli" }
substrate-frame-cli = { version = "2.0.0", path = "../../../utils/frame/frame-utilities-cli" }
structopt = "0.3.14"
frame-system = { version = "2.0.0", path = "../../../frame/system" }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }

[features]
bench = []
