[package]
name = "substrate-test-runtime-client"
version = "2.0.0"
authors = ["Abel Technologies abelbeertech@outlook.com"]
edition = "2018"
license = "Apache-2.0"
homepage = "http://www.abel.beer"
repository = "https://github.com/abelbeertech/abel-bkchain"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-light = { version = "2.0.0", path = "../../../client/light" }
sp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
sc-block-builder = { version = "0.8.0", path = "../../../client/block-builder" }
substrate-test-client = { version = "2.0.0", path = "../../client" }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
substrate-test-runtime = { version = "2.0.0", path = "../../runtime" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
sp-api = { version = "2.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
codec = { package = "parity-scale-codec", version = "1.3.1" }
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sc-consensus = { version = "0.8.0", path = "../../../client/consensus/common" }
sc-service = { version = "0.8.0", default-features = false, path = "../../../client/service" }
futures = "0.3.4"
